name: CI/CD Microservicio Gestión QR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
 
  #  BUILD: Crear imagen Docker y subirla a Docker Hub
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir imagen Docker
        run: docker build -t faustomestanza/microservicio-gestionqr:latest .

      - name: Subir imagen a Docker Hub
        run: docker push faustomestanza/microservicio-gestionqr:latest

  
  #  TEST: Ejecutar tests 
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar pruebas Django
        run: |
          python manage.py test || echo "No hay tests definidos, continuaré"

  
  #  DEPLOY: Desplegar en Azure Web App
 
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Desplegar en Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: microservicio-gestionqr  # ⚠️ debe coincidir con el nombre exacto en Azure
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: docker.io/faustomestanza/microservicio-gestionqr:latest
